### ISSUE TITLE
Issues using mixins

### ISSUE THREAD

**Issue by rs3d** [facing-dev/vue-facing-decorator#105]
Hi, 

I'm trying to create a working class component with a mixin but I'm receiving following error:
![image](https://github.com/facing-dev/vue-facing-decorator/assets/1399149/c6b3f06b-c9b8-421b-8032-c5374b80824a)

I've tried already multiple ways but can't get it to work. 

Example: 
https://stackblitz.com/edit/vitejs-vite-solmwi?file=src%2Fcomponents%2FHelloWorld.vue

When I remove the 'MyMixin' in L:14 it's rendering
![image](https://github.com/facing-dev/vue-facing-decorator/assets/1399149/d2ab199d-8233-4859-9831-148bd3ed8239)

As I understand using ` "experimentalDecorators": true,` as tsconfig setting I don't need to wrap the default export with toNative.
Even using toNative in my example doesn't help.

**Comment by rdhelms** [comment]
Hi @rs3d - I think you have a couple different options:
1. You could change your Mixin to be exported from a `.ts` file instead of a `.vue` file and still use the `extends mixins(MyMixin)` method:
    - https://stackblitz.com/edit/vitejs-vite-7nvlws?file=src%2Fmixins%2FMyMixin.ts
3. You could continue exporting the Mixin from a `.vue` file and use `@Component({ mixins: [MyMixin] })` instead:
    - https://stackblitz.com/edit/vitejs-vite-njr8rr?file=src%2Fcomponents%2FHelloWorld.vue

Do either of those options work for you?

**Comment by calandnong** [comment]
这个问题解决了吗？我看目前最新版本还在报错？
