### ISSUE TITLE
Create Mixins as Class Components instead of defineComponent() ?

### ISSUE THREAD

**Issue by Pazulay** [facing-dev/vue-facing-decorator#12]
In the Docs it looks like you can only import mixins into class components with mixins? option, but you have to create the mixins with defineComponent function.

Is there a way I can create a mixin with class component syntax?

Current project:
```
// example-mixin.ts
export const ExampleMixin = defineComponent({
  data() {
    return {
      foo: 0,
      bar: 0,
    };
  },
  created() {
    this.Function();
  },
  methods: {
    ...
      }
    },
  },
});

// example-component.ts

@Component({ mixin: [ExampleMixin] })
```

Desired:
```
// example-mixin.ts
@Component({})
export default class ExampleMixin extends Vue {
 public foo = number;
 public bar = number;
}

// example-component.ts
@Component({ mixin: [ExampleMixin] })
...
```

**Comment by ruojianll** [comment]
@Pazulay 
Your desired code should work in the current version. Because of @Component is not same to @ComponentBase. @Component returns vue options component. @ComponentBase returns a vue-facing-decorator class component.

So a @Component decorated class could be used as normal vue component everywhere, includes passing it into `mixin?` array directly.

More, if you want to mixin a @ComponentBase class component, you could extends it directly. In implementation, extends a class component  is same to mixin it as first component in mixin array.

```ts
@ComponentBase({})
class ExampleExtends extends Vue {
 public foo = number;
 public bar = number;
}

@Component
class MyComponent extends ExampleExtends{
}
```

**Comment by zhoulujun** [comment]
我发现，在父类的 @Props ，在子类不重复声明，就拿不到。
案例如下：
```typescript

interface Props {
  panelModel: IPanelModel<DatasourceMysql, BaseQuery>
}

@ComponentBase({})
class ExampleExtends extends TSX<Props>()(Vue) implements Props {
 public foo = number;
 public bar = number;
 @Prop({ required: true }) panelModel: IPanelModel;
}
```
在子类
```typescript
interface Props {
  panelModel: IPanelModel<DatasourceMysql, BaseQuery>
}
@Component
class MyComponent extends TSX<Props>()(BaseQueryPanel) implements Props {
   created() {
       console.log(this.panelModel)// undefined 
   }

}

```

需要在 MyComponent  重载  @Prop({ required: true }) panelModel: IPanelModel;  才可以拿到。
