### ISSUE TITLE
Unit test with @vue/test-utils

### ISSUE THREAD

**Issue by rock288** [facing-dev/vue-facing-decorator#95]
Is the vue-facing-decorator library compatible with @vue/test-utils? If yes, could you please provide guidance on how to use it? Thank you.

**Comment by odemc** [comment]
I have the same question. Props are undefined during test run and I can't find any solution how to fix it.

**Comment by rdhelms** [comment]
@rock288 @odemc As far as I'm aware, most people have unfortunately found it necessary to migrate to vitest because of issues with @vue/test-utils and . Have either of you had any luck using @vue/test-utils since making this issue?

https://github.com/facing-dev/vue-facing-decorator/issues/54#issuecomment-1500019388
https://github.com/facing-dev/vue-facing-decorator/issues/33#issuecomment-1410648544
